name: umay_client
description: "Umay Sentinel - Network Security & Monitoring App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0' # Fedora'daki Flutter sürümünle uyumlu olması için

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # --- Eklediğimiz Paketler ---
  http: ^1.6.0              # Backend API ile konuşmak için
  fl_chart: ^0.63.0         # Ağ trafiği grafikleri (Dashboard için)
  provider: ^6.0.5          # Uygulama içindeki veriyi yönetmek (State Management)
  google_fonts: ^6.1.0      # Daha profesyonel bir tipografi için
  percent_indicator: ^4.2.3 # Tarama durumunu vs. göstermek için
  google_sign_in: 6.2.1
  flutter_dotenv: ^6.0.0
  wireguard_flutter: ^0.0.1
  # ---------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Asset tanımlamaları burada başlar
  assets:
    - assets/brands/  # Marka ikonlarını buraya toplu olarak ekledik
    - .env